apiVersion: v1
kind: ReplicationController
metadata:
  selfLink: 
  resourceVersion: 
  uid: 
  creationTimestamp: 
  managedFields: []
  name: rc
  namespace:
spec:
  replicas: 2
  selector:
    app: santander-phpinfo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: santander-phpinfo
    spec:
      containers:
        - name: php
          image: 'index.docker.io/ismaldk/santander-phpinfo:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: nombre_alumno
              value: ismael
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status: {}
